Changes priority class to system-node-critical to improve chances to …
giantswarm/linkerd2-cni-app pull request #99
Opened 2023-02-15 05:39 UTC by danibaeyens

…be correctly scheduled

This PR modifies the priority class of linkerd CNI to improve chances to be scheduled on situations where there is higher pressure on the node. As linkerd is a critical component on a cluster, having it broken can lead to services unable to properly communicate with each other, or falling back to unmeshed communication, which can create other issues.

## Checklist

- [ ] Automated test are working (for chart changes)
- [x] I am confident my changes don't break existing installations (for chart changes)
- [x] Changelog entry has been added

2023-02-17 08:00 UTC, Gacko commented
@mcharriere Is this is a good default value? Because if so you could also propose this to upstream.

2023-02-17 08:00 UTC, Gacko approved these changes

2023-02-17 08:02 UTC, Gacko requested changes
@danibaeyens Could you please run [`helm-docs`](https://github.com/norwoodj/helm-docs) or at least update the default value listed in the [README.md](https://github.com/giantswarm/linkerd-cni-app/blob/main/helm/linkerd-cni/README.md)? Thank you very much!

2023-02-17 08:05 UTC, mcharriere commented
Hi there. Upstream already discussed this and decided to go for `empty` as default value as far as I remember. 
We were considering using `giantswarm-critical` instead of `system-node-critical`. 

The later is the highest priorityclass, and it seems odd.

2023-02-17 08:30 UTC, danibaeyens commented
oh! ok. 
It's true that it might not be critical for the cluster as such, but it's definitely needs to have more priority than normal workloads. I'm fine with `giantswarm-critical` for both `linkerd2-cni-app` and `linkerd-control-plane-app`. WDYT?

2023-02-17 08:33 UTC, mcharriere commented
> I'm fine with giantswarm-critical for both linkerd2-cni-app and linkerd-control-plane-app. WDYT?

Sounds good @danibaeyens , thank you! 

FYI: there is a small bug in our CI fixed by https://github.com/giantswarm/devctl/commit/975df05655858143392d4b9be9c79906aa361163. Although we haven't update this repo yet with the fix.

2023-02-17 09:15 UTC, Gacko approved these changes

2023-02-17 09:16 UTC, Gacko commented
@mcharriere Just merged the changes required to make external contribution work (fixed the values schema check).

2023-02-17 09:17 UTC, mcharriere approved these changes

2023-02-17 09:18 UTC, Gacko commented
Seems the CircleCI chart tests are required for this PR by GitHub repository configuration but not triggered by CircleCI configuration inside the repository.

@mcharriere Could you have a look at this?

2023-02-27 08:56 UTC, mcharriere commented
Thanks @danibaeyens for your contributions. We still need to sort out some things with our CI. Because of that, I created another PR with your commit and will close this one.

2023-02-27 08:56 UTC, closed without merging